/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect,useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/monde.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.tourne.play()
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="URF-Height" position={[0, 2.42, 0]} scale={2.29}>
          <mesh name="Icosphere003" geometry={nodes.Icosphere003.geometry} material={materials.watr} />
          <mesh name="Icosphere003_1" geometry={nodes.Icosphere003_1.geometry} material={materials.Lampd} />
          <mesh name="Icosphere003_2" geometry={nodes.Icosphere003_2.geometry} material={materials.Lampd_Ice} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/monde.glb')

export default Model